name = "tinynav"
main = "src/worker.ts"
compatibility_date = "2026-01-14"

[build]
command = "npm run build"

[assets]
directory = "dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "CLOUDNAV_DB"
class_name = "CloudNavDB"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["CloudNavDB"]

